---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.dotenvSecret.name }}
  namespace: {{ .Values.namespace }}
data:
  .env: {{ .Values.secret.dotenvSecret.data.envContent | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.registryCredentials.name }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secret.registryCredentials.dockerconfigjson | quote }}
